import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const GROSSESSE_DATA = {
  theme: 'LA GROSSESSE NORMALE',
  subThemes: [
    {
      name: 'Datation et Consultations',
      questions: [
        { order: 1, text: "Quelles sont les propositions vraies concernant la date de début théorique de grossesse (DDG) ?", choiceA: "DDG = Date des dernières règles (DDR) + 7 jours.", choiceB: "la Date de Début de Grossesse (DDG) = Date des Dernières Règles (DDR)+ 14 jours.", choiceC: "En cas de FIV, le DDG correspond à la date de la ponction ovocytaire.", choiceD: "La datation par échographie est précise à +/- 7 jours.", choiceE: "La mesure de la Longueur Cranio-Caudale (LCC) à 12 SA se situe entre 45 et 84 mm.", correctAnswer: "B,C,E", explanation: "la Date de Debut de Grossesse (DDG) = Date des Dernières Règles (compter le premier jour des règles) + 14j ou date de ponction en FIV. L'échographie est précise à +/- 3 jours. La LCC à 12 SA est bien comprise entre 45 et 84 mm." },
        { order: 2, text: "Concernant le calendrier de suivi d'une grossesse normale, quelles sont les affirmations exactes ?", choiceA: "Il comprend 8 consultations prénatales obligatoires.", choiceB: "La première consultation doit avoir lieu avant 15 SA.", choiceC: "Une consultation post-partum est obligatoire dans les 6 à 8 semaines après l'accouchement.", choiceD: "Les consultations deviennent hebdomadaires dès le 6ème mois.", choiceE: "Le suivi peut être effectué par un médecin généraliste ou une sage-femme.", correctAnswer: "A,C,E", explanation: "Le suivi classique comporte 8 consultations (1/mois) et 1 consultation post-partum (6/8 semaines). Le suivi peut être assuré par un medecin generaliste, un gynécologue ou une sage-femme." },
        { order: 3, text: "Quels examens biologiques sont obligatoires lors du bilan du 1er trimestre (avant 15 SA) ?", choiceA: "Groupe sanguin (ABO, Rhésus, Kell) et RAI.", choiceB: "Sérologies Toxoplasmose et Rubéole.", choiceC: "Sérologie VIH.", choiceD: "Sérologie Syphilis et Ag HBs.", choiceE: "Recherche de la Trisomie 21 (Triple Test).", correctAnswer: "A,B,D", explanation: "Groupe/Rh, Toxo, Rubéole, Syphilis et HBs sont obligatoires. Le VIH doit être systématiquement proposé mais nécessite l'accord de la patiente. Le dépistage de la T21 est proposé mais non obligatoire." },
        { order: 4, text: "Quelles sont les modalités de surveillance de la Toxoplasmose et de la Rubéole chez une femme enceinte séronégative ?", choiceA: "Toxoplasmose : contrôle mensuel jusqu'à l'accouchement.", choiceB: "Rubéole : contrôle mensuel jusqu'à l'accouchement.", choiceC: "Rubéole : contrôle mensuel jusqu'à 20 SA.", choiceD: "Toxoplasmose : contrôle tous les trimestres uniquement.", choiceE: "Une éducation sur les mesures hygiéno-diététiques est nécessaire pour la toxoplasmose.", correctAnswer: "A,C,E", explanation: "Si séronégative, la Toxoplasmose se surveille tous les mois. La Rubéole se surveille tous les mois mais s'arrête à 20 SA. Les mesures d'hygiène (viande cuite, lavage des mains) sont essentielles pour la toxoplasmose." },
        { order: 5, text: "Concernant la Bandelette Urinaire (BU) effectuée lors de chaque consultation mensuelle, que recherche-t-on ?", choiceA: "La présence de nitrites.", choiceB: "La glycosurie.", choiceC: "L'albuminurie (protéinurie).", choiceD: "La présence de sang (hématurie).", choiceE: "Le pH urinaire.", correctAnswer: "B,C", explanation: "la recherche de la glycosurie et de l'albuminurie est obligatoire tous les mois par bandelette urinaire pour dépister le diabète gestationnel et la prééclampsie." },
        { order: 6, text: "À quel moment le dépistage du diabète gestationnel (HGPO à 75g) est-il recommandé s'il existe des facteurs de risque ?", choiceA: "Entre 11 et 14 SA.", choiceB: "Entre 20 et 24 SA.", choiceC: "Entre 24 et 28 SA.", choiceD: "Entre 32 et 35 SA.", choiceE: "Uniquement si la glycosurie à la BU est positive.", correctAnswer: "C", explanation: "L'HGPO (Hyperglycémie Provoquée par Voie Orale) à 75g de glucose est réalisée entre 24 et 28 SA chez les patientes présentant des facteurs de risque." },
        { order: 7, text: "Quelles sont les caractéristiques des trois échographies recommandées pendant la grossesse ?", choiceA: "Elles sont obligatoires pour la prise en charge à 100%.", choiceB: "L'écho T1 (11-13.6 SA) sert à la datation et à la mesure de la clarté nucale.", choiceC: "L'écho T2 (20-24 SA) est principalement morphologique.", choiceD: "L'écho T3 (32 SA) évalue la croissance fœtale et la présentation.", choiceE: "Chez les patientes âgée de la vingtaine l'echographie n'est pas nécessaire lors du suivi de la grossesse.", correctAnswer: "B,C,D", explanation: "T1=datation, T2=morphologie, T3=croissance." },
        { order: 8, text: "Quelle supplémentation médicamenteuse est systématiquement recommandée au 3ème trimestre ?", choiceA: "Le fer.", choiceB: "La Vitamine D (1 ampoule).", choiceC: "Le Calcium.", choiceD: "L'Acide Folique.", choiceE: "Le Magnésium.", correctAnswer: "B", explanation: "Une dose unique de Vitamine D est recommandée au début du 7ème mois (ou T3). Le fer n'est supplémenté qu'en cas d'anémie prouvée (Hb < 10,5 g/dL au 2e trimestre)." },
        { order: 9, text: "Concernant l'Acide Folique (Vitamine B9), quelles sont les recommandations ?", choiceA: "Dose de 0,4 mg/j en prévention primaire.", choiceB: "Doit être débuté 2 mois avant la conception.", choiceC: "Doit être poursuivi jusqu'à 12 SA.", choiceD: "Dose de 5 mg/j si antécédents d'anomalie de fermeture du tube neural.", choiceE: "Permet de prévenir les malformations cardiaques.", correctAnswer: "A,B,C,D", explanation: "La B9 prévient les anomalies du tube neural (Spina Bifida). Elle doit être prise en péri-conceptionnel (2 mois avant) jusqu'à la fin du T1." },
        { order: 10, text: "À quel terme doit-on réaliser le prélèvement vaginal pour la recherche du Streptocoque B ?", choiceA: "Entre 24 et 28 SA.", choiceB: "Entre 28 et 32 SA.", choiceC: "Entre 35 et 37 SA.", choiceD: "Uniquement si la patiente a des contractions.", choiceE: "Ce prélèvement est inutile si une césarienne est prévue.", correctAnswer: "C", explanation: "Le dépistage systématique du portage de Streptocoque B se fait par prélèvement vaginal entre 35 et 37 SA." },
        { order: 11, text: "Quelle est la formule de calcul théorique de la Hauteur Utérine (HU) entre 16 et 32 SA ?", choiceA: "HU (cm) = Nombre de SA.", choiceB: "HU (cm) = Nombre de SA + 4.", choiceC: "HU (cm) = Nombre de SA - 4.", choiceD: "À 20 SA, la HU théorique est de 16 cm.", choiceE: "À 28 SA, la HU théorique est de 24 cm.", correctAnswer: "C,D,E", explanation: "Entre 16 et 32 SA, la formule est : Nombre de SA - 4. Exemple : 28 SA - 4 = 24 cm. Au-delà de 32 SA, la Hauteur Utérine = 28+ 0.5cm (pour chaque semaine au-delà de la 32e SA)." },
        { order: 12, text: "Quels éléments composent le \"Score de Manning\" évaluant le bien-être fœtal ?", choiceA: "Mouvements respiratoires et fœtaux.", choiceB: "Tonus et réactivité du rythme cardiaque.", choiceC: "Quantité de liquide amniotique.", choiceD: "Couleur du liquide amniotique.", choiceE: "Mesure de la clarté nucale.", correctAnswer: "A,B,C", explanation: "Le score de Manning repose sur 5 critères : mouvements respiratoires, mouvements fœtaux globaux, tonus fœtal, réactivité du RCF et volume de liquide amniotique." },
        { order: 13, text: "Une Hauteur Utérine (HU) excessive peut faire suspecter quels diagnostics ?", choiceA: "Un Retard de Croissance Intra-Utérin (RCIU).", choiceB: "Un Hydramnios (excès de liquide).", choiceC: "Une Macrosomie fœtale.", choiceD: "Une grossesse multiple.", choiceE: "Un Oligoamnios.", correctAnswer: "B,C,D", explanation: "Une HU supérieure à la normale suggère un gros bébé (macrosomie), trop de liquide (hydramnios) ou plusieurs bébés (jumeaux/triplets)." },
        { order: 14, text: "Quels sont les critères de définition de l'anémie chez la femme enceinte ?", choiceA: "Hémoglobine < 12 g/dL au 1er trimestre.", choiceB: "Hémoglobine < 11 g/dL au 1er trimestre.", choiceC: "Hémoglobine < 10,5 g/dL au 2ème trimestre.", choiceD: "Une carence martiale est définie par une ferritine < 12 µg/L.", choiceE: "L'anémie est physiologique au T2 par hémodilution.", correctAnswer: "B,C,D", explanation: "Les seuils d'anémie sont < 11 (T1) et < 10,5 (T2/T3). L'hémodilution explique la baisse, mais les seuils cliniques restent ceux-là." },
        { order: 15, text: "Quels sont les facteurs de risque de \"grossesse difficile/à risque\" ?", choiceA: "Âge maternel < 15 ans ou > 35 ans.", choiceB: "IMC > 25 (surpoids/obésité).", choiceC: "Antécédents de césarienne ou de chirurgie utérine.", choiceD: "Tabagisme et consommation d'alcool.", choiceE: "Précarité socio-économique.", correctAnswer: "A,B,C,D,E", explanation: "Tous ces facteurs sont décrits comme augmentant le risque de grossesse pathologique nécessitant un suivi plus étroit." },
        { order: 16, text: "Concernant le dépistage de la Trisomie 21 au 1er trimestre, que comprend le \"risque combiné\" ?", choiceA: "L'âge maternel.", choiceB: "La mesure de la clarté nucale (échographie).", choiceC: "Les marqueurs sériques (PAPP-A et fraction libre de l'hCG).", choiceD: "Le groupe sanguin de la mère.", choiceE: "La recherche de l'ADN libre circulant (en première intention).", correctAnswer: "A,B,C", explanation: "Le calcul du risque combiné du T1 associe l'âge de la patiente, la clarté nucale (mesurée entre 11 et 13.6 SA) et le dosage de deux hormones (PAPP-A et hCG-beta)." },
        { order: 17, text: "Quel examen est nécessaire pour confirmer une grossesse si le test urinaire est douteux ?", choiceA: "Une radiographie de l'abdomen.", choiceB: "Un dosage plasmatique de la béta-hCG.", choiceC: "Une échographie pelvienne dès la 1ère SA.", choiceD: "Un toucher vaginal (utérus sphérique).", choiceE: "Une mesure de la température basale (plateau thermique > 15j) confirme la grossesse.", correctAnswer: "B", explanation: "La béta-hCG plasmatique est le gold standard. L'écho est utile dès 5 SA. Le plateau thermique long est un signe indirect d'activité du corps jaune de grossesse mais ne confirme pas la grossesse." },
        { order: 18, text: "Quels sont les objectifs de la consultation prénatale du 4ème mois ?", choiceA: "Réaliser une échographie de morphologie.", choiceB: "Dépister les risques médico-psycho-sociaux.", choiceC: "Un examen clinique obstétrical : HU, BDC, mouvements actifs fœtaux (MAF), poids, PA.", choiceD: "C'est une séance de préparation à l'accouchement obligatoire.", choiceE: "La sérologie de la rubéole si elle était négative au premier trimestre.", correctAnswer: "B,C,E", explanation: "Consultation du 4e mois (16–20 SA) : examen clinique obstétrical (HU, BDC, MAF, poids, PA), sérologie toxoplasmose et rubéole si négatives au T1, bandelette urinaire." },
      ],
    },
    {
      name: 'Modifications physiologiques de la grossesse et Signes cliniques',
      questions: [
        { order: 1, text: "Quelles modifications hématologiques sont considérées comme normales pendant la grossesse ?", choiceA: "Une hyperleucocytose (jusqu'à 15 000 GB/mm3).", choiceB: "Une baisse du taux d'hémoglobine (hémodilution).", choiceC: "Une augmentation de la Vitesse de Sédimentation (VS).", choiceD: "Une baisse des facteurs pro-coagulants.", choiceE: "Une augmentation du fibrinogène.", correctAnswer: "A,B,C,E", explanation: "La grossesse est un état d'hypercoagulabilité (hausse du fibrinogène) avec une anémie relative (Anémie à partir de 10,5g/dl à partir du 2e trimestre) par dilution et une hausse modérée des globules blancs, limite maximale normale (15000)." },
        { order: 2, text: "Quelles sont les modifications rénales et urinaires physiologiques ?", choiceA: "Augmentation du Débit de Filtration Glomérulaire (DFG) de 40%.", choiceB: "Baisse de la créatininémie et de l'urée.", choiceC: "Dilatation des uretères (surtout à droite).", choiceD: "Diminution du débit cardiaque.", choiceE: "Glycosurie physiologique (par baisse du seuil de réabsorption).", correctAnswer: "A,B,C,E", explanation: "Le rein travaille plus (hausse DFG), la créatinine baisse. La dilatation droite est due à la dextrorotation de l'utérus (compression mécanique de l'utérus sur l'uretère droite, entrainant une légère stase favorisant les infections du côté droit). Le débit cardiaque, lui, augmente." },
        { order: 3, text: "Parmi les signes cliniques du 1er trimestre, quels sont les deux signes les plus fréquents ?", choiceA: "Tension mammaire.", choiceB: "Pollakiurie (envie fréquente d'uriner).", choiceC: "Hypersomnie et fatigue.", choiceD: "Nausées et vomissements.", choiceE: "Oedèmes des membres inférieurs.", correctAnswer: "A,D", explanation: "Le diagnostic de grossesse repose sur la clinique. L'interrogatoire retrouve un retard de règles et les signes sympathiques : tension mammaire, somnolence, asthénie, pollakiurie, nausées et vomissements. Les œdèmes apparaissent plutôt au 3ème trimestre." },
        { order: 4, text: "Quels signes cliniques peuvent apparaître au 3ème trimestre d'une grossesse normale ?", choiceA: "Vergetures et chloasme (masque de grossesse).", choiceB: "Lombalgies et sciatalgies.", choiceC: "Pyrosis (remontées acides).", choiceD: "Crampes des membres inférieurs.", choiceE: "Disparition des mouvements fœtaux.", correctAnswer: "A,B,C,D", explanation: "La compression mécanique et les hormones causent ces désagréments. La disparition des mouvements fœtaux est une urgence absolue et n'est pas normale." },
        { order: 5, text: "Quels vaccins sont FORMELLEMENT CONTRE-INDIQUÉS pendant la grossesse (vaccins vivants) ?", choiceA: "Le ROR (Rougeole-Oreillons-Rubéole).", choiceB: "La Varicelle.", choiceC: "La Grippe.", choiceD: "Le BCG (Tuberculose).", choiceE: "Le Tétanos.", correctAnswer: "A,B,D", explanation: "Les vaccins vivants atténués sont proscrits. La grippe (inactivé) est au contraire recommandée." },
        { order: 6, text: "Quelle est la prise de poids totale recommandée pour une grossesse normale ?", choiceA: "5 à 7 kg.", choiceB: "9 à 12 kg.", choiceC: "15 à 20 kg.", choiceD: "500g par mois au 1er trimestre.", choiceE: "2 kg par mois au 3ème trimestre.", correctAnswer: "B,D", explanation: "La moyenne est de 9-12kg. La prise de poids est faible au premier trimestre (500g/mois)." },
        { order: 7, text: "Quels sont les facteurs de risque de dysthyroïdie à rechercher chez la femme enceinte ?", choiceA: "Âge > 30 ans.", choiceB: "Antécédents personnels ou familiaux de pathologie thyroïdienne.", choiceC: "Présence d'un goitre ou d'un diabète de type 1.", choiceD: "Antécédent d'accouchement prématuré.", choiceE: "Antécédent d'irradiation cervicale.", correctAnswer: "A,B,C,D,E", explanation: "Tous ces éléments imposent une vigilance sur la fonction thyroïdienne (dosage TSH)." },
      ],
    },
    {
      name: 'Suivi Biologique et Dépistages',
      questions: [
        { order: 1, text: "À quel terme propose-t-on le dépistage de la Trisomie 21 par les marqueurs sériques du 2ème trimestre si celui du 1er n'a pas été fait ?", choiceA: "Entre 11 et 14 SA.", choiceB: "Entre 14 et 18 SA.", choiceC: "Entre 20 et 24 SA.", choiceD: "Uniquement après l'échographie T2.", choiceE: "Ce test dose l'hCG et l'AFP.", correctAnswer: "B,E", explanation: "Si le dépistage combiné du T1 est manqué, on propose le Triple Test (hCG + AFP) entre 14 et 18 SA." },
        { order: 2, text: "Quand doit-on administrer des Gamma-globulines anti-D chez une femme Rhésus négatif (conjoint Rh+) ?", choiceA: "Systématiquement à 28 SA.", choiceB: "Dans les 72h après un événement à risque (métrorragies, amniocentèse).", choiceC: "À la naissance si le bébé est Rhésus positif.", choiceD: "Uniquement si les RAI sont positives.", choiceE: "Uniquement au 1er trimestre.", correctAnswer: "A,B,C", explanation: "Prophylaxie antepartum planifiée : dose unique de 300 microgrammes à 28-30 SA. En cas de complication : dans les 72h. Prophylaxie postpartum si bébé Rh+." },
        { order: 3, text: "Quelles sont les valeurs cibles d'Hémoglobine pour supplémenter en fer au 2ème trimestre ?", choiceA: "Hb < 12 g/dL.", choiceB: "Hb < 11 g/dL.", choiceC: "Hb < 10,5 g/dL.", choiceD: "Indépendamment du taux, si la patiente est fatiguée.", choiceE: "si la ferritine est < 12 µg/L.", correctAnswer: "C,E", explanation: "La supplémentation martiale n'est pas systématique ; elle se discute sous 10,5 g/dL ou si les réserves (ferritine) sont effondrées." },
        { order: 4, text: "Le dépistage de la Syphilis (VDRL-TPHA) est :", choiceA: "Facultatif.", choiceB: "Obligatoire lors du bilan initial.", choiceC: "À renouveler au 3ème trimestre si patiente à risque.", choiceD: "Toujours associé à une sérologie Hépatite C.", choiceE: "Réalisé uniquement sur prélèvement vaginal.", correctAnswer: "B,C", explanation: "Obligatoire au T1, il peut être répété si le mode de vie expose à un risque de contamination." },
        { order: 5, text: "Quels éléments sont recherchés lors de l'examen clinique mensuel lors du suivi de la grossesse ?", choiceA: "Prise de poids et Tension Artérielle.", choiceB: "Mesure de la Hauteur Utérine.", choiceC: "Bruits du cœur fœtal (dès 10-12 SA).", choiceD: "Toucher vaginal systématique.", choiceE: "Perception des mouvements fœtaux par la mère au 1er trimestre.", correctAnswer: "A,B,C", explanation: "Le toucher vaginal n'est plus systématique s'il n'y a pas d'appel clinique (contractions, pertes)." },
        { order: 6, text: "À partir de quel terme les bruits du cœur fœtal sont-ils audibles au Doppler fœtal portatif ?", choiceA: "5 SA.", choiceB: "10-12 SA.", choiceC: "20 SA.", choiceD: "Au moment de l'échographie T2.", choiceE: "Uniquement au stéthoscope de Pinard.", correctAnswer: "B", explanation: "L'activité cardiaque est visible à l'écho dès 5-6 SA, et audible au Doppler portatif à partir de 10-12 SA." },
        { order: 7, text: "Quelle est la limite de viabilité fœtale ?", choiceA: "> 20 SA et 400 g.", choiceB: "> 22 SA et/ou 500 g.", choiceC: "> 24 SA et 600 g.", choiceD: "Indépendamment du poids si le terme est > 22 SA.", choiceE: "Uniquement si le bébé respire.", correctAnswer: "B", explanation: "Selon les critères de l'OMS, la viabilité est fixée à 22 SA ou un poids de 500g." },
        { order: 8, text: "Qu'est-ce que l'allo-immunisation Rhésus ?", choiceA: "Une infection bactérienne transplacentaire.", choiceB: "La production d'anticorps maternels contre les globules rouges du fœtus.", choiceC: "Elle ne concerne que les mères Rhésus négatif.", choiceD: "Elle peut provoquer une anémie fœtale grave (anasarque).", choiceE: "Elle se soigne par antibiotiques.", correctAnswer: "B,C,D", explanation: "C'est une incompatibilité sanguine entre la mère (Rh-) et le fœtus (Rh+), prévenue par l'injection de sérum anti-D." },
      ],
    },
    {
      name: 'Pathologies, Travail et Divers',
      questions: [
        { order: 1, text: "Quels signes imposent une consultation en URGENCE au 3ème trimestre ?", choiceA: "Diminution ou arrêt des mouvements fœtaux.", choiceB: "Métrorragies (saignements).", choiceC: "Contractions utérines régulières et douloureuses.", choiceD: "Perte de liquide (suspicion de rupture des membranes).", choiceE: "Fièvre ou brûlures urinaires.", correctAnswer: "A,B,C,D,E", explanation: "Tous ces signes peuvent traduire une pathologie aiguë (HRP, MAP, RPM, infection) nécessitant une consultation d'urgence." },
        { order: 2, text: "En cas de sérologie Rubéole négative au T1, que doit faire la patiente ?", choiceA: "Se faire vacciner immédiatement.", choiceB: "Faire un contrôle mensuel jusqu'à 20 SA.", choiceC: "Se faire vacciner après l'accouchement (en post-partum).", choiceD: "Éviter le contact avec des enfants malades (éruption).", choiceE: "Prendre de l'acide folique.", correctAnswer: "B,C,D", explanation: "On ne vaccine jamais la Rubéole pendant la grossesse (vaccin vivant atténué). On surveille la séroconversion et on vaccine après la naissance." },
        { order: 3, text: "Une patiente présente une glycosurie positive à la BU. Quelle est la conduite à tenir ?", choiceA: "Rien, c'est physiologique.", choiceB: "Réaliser une glycémie à jeun ou une HGPO.", choiceC: "Interdire tout sucre à la patiente.", choiceD: "Rechercher une infection urinaire associée (ECBU).", choiceE: "Hospitaliser immédiatement.", correctAnswer: "B", explanation: "Une glycosurie nécessite de vérifier l'absence de diabète. Une infection urinaire est à rechercher en cas de point d'appel (ECBU)." },
        { order: 4, text: "Quelles sont les recommandations concernant les soins dentaires chez la femme enceinte ?", choiceA: "Ils sont contre-indiqués pendant la grossesse.", choiceB: "Un examen bucco-dentaire est recommandé.", choiceC: "Les infections dentaires augmentent le risque d'accouchement prématuré.", choiceD: "On ne peut pas faire de radiographie dentaire.", choiceE: "L'anesthésie locale chez le dentiste est possible.", correctAnswer: "B,C,E", explanation: "L'hygiène dentaire est capitale (risque de MAP). Les soins courants sont possibles et encouragés." },
        { order: 5, text: "Qu'est-ce que l'hémodilution physiologique de la grossesse ?", choiceA: "Une baisse de la quantité de plasma.", choiceB: "Une augmentation du volume plasmatique supérieure à l'augmentation de la masse globulaire.", choiceC: "Une cause de baisse de l'albumine plasmatique.", choiceD: "Un mécanisme protégeant des thromboses.", choiceE: "Elle explique la baisse du taux d'hémoglobine.", correctAnswer: "B,C,E", explanation: "Le volume de sang augmente, mais comme il y a 'plus d'eau que de cellules', les concentrations (Hb, albumine) baissent mécaniquement." },
        { order: 6, text: "Le suivi post-natal comprend quel élément obligatoire pour la mère ?", choiceA: "Une consultation de rééducation abdominale.", choiceB: "Une consultation post-natale (6-8 semaines après).", choiceC: "Un frottis cervico-utérin (s'il n'est pas à jour).", choiceD: "Une discussion sur la contraception.", choiceE: "Un examen des seins.", correctAnswer: "B,C,D,E", explanation: "La consultation post-natale fait le point sur la récupération physique, la contraception, le psychisme et le dépistage du cancer du col." },
      ],
    },
  ],
};

const COMPLICATIONS_DATA = {
  theme: 'Principales complications de la grossesse',
  subThemes: [
    {
      name: 'Principales complications de la grossesse',
      questions: [
        { order: 1, text: "Une patiente de 26 ans consulte pour des saignements vaginaux peu abondants et noirâtres à 7 semaines d'aménorrhée, associés à une douleur à l'épaule droite. Elle a un antécédent d'infection génitale haute. Quels diagnostics ou facteurs de risque sont cohérents avec ce tableau ?", choiceA: "Une grossesse extra-utérine.", choiceB: "La douleur à l'épaule suggère la présence de sang dans la cavité péritonéale (hémopéritoine).", choiceC: "L'antécédent d'infection génitale haute est un facteur de risque majeur de grossesse extra-utérine.", choiceD: "Il s'agit probablement d'une grossesse molaire.", choiceE: "Le tabagisme est un facteur de risque reconnu pour cette pathologie.", correctAnswer: "A,B,C,E", explanation: "Les saignements noirâtres, la douleur latéralisée et l'irradiation à l'épaule (signe d'irritation du diaphragme par le sang) sont typiques de la grossesse extra-utérine. Les principaux facteurs de risque incluent le tabac, les antécédents d'infections tubaires et la chirurgie pelvienne." },
        { order: 2, text: "Une patiente à 10 semaines d'aménorrhée présente des saignements francs avec du sang rouge et des caillots, accompagnés de douleurs pelviennes à type de contractions. Au toucher vaginal, le col est ouvert. L'échographie montre un sac gestationnel aplati sans activité cardiaque. Quels éléments sont exacts ?", choiceA: "Le diagnostic le plus probable est une fausse couche spontanée.", choiceB: "La disparition récente des signes sympathiques (nausées, seins tendus) confirme cette hypothèse.", choiceC: "Une injection d'immunoglobulines anti-D est nécessaire si la patiente est de groupe sanguin Rhésus négatif.", choiceD: "L'aspiration chirurgicale est la seule option thérapeutique possible.", choiceE: "Une analyse anatomopathologique des tissus expulsés est recommandée.", correctAnswer: "A,E", explanation: "La douleur de type 'contractions' associée à un col ouvert et des saignements rouges définit l'expulsion d'une fausse couche. Le traitement peut être médical ou chirurgical. La prévention de l'immunisation Rhésus n'est pas recommandée avant 12SA vu le risque quasi nul d'alloimmunisation." },
        { order: 3, text: "Une sage-femme examine une patiente au premier trimestre présentant des vomissements très intenses et une hauteur utérine excessive pour le terme. L'échographie montre un aspect en \"tempête de neige\" sans embryon. Quelles sont les caractéristiques de cette pathologie ?", choiceA: "Il s'agit d'une grossesse molaire (môle hydatiforme).", choiceB: "Le taux d'hormone de grossesse est généralement extrêmement élevé.", choiceC: "On retrouve souvent des kystes sur les deux ovaires à l'échographie.", choiceD: "La complication majeure à long terme est le choriocarcinome (tumeur maligne).", choiceE: "Le traitement repose sur une chimiothérapie par méthotrexate en première intention.", correctAnswer: "A,B,C,D", explanation: "La môle hydatiforme nécessite une aspiration utérine sous contrôle échographique. Le suivi prolongé du taux d'hormone est impératif pour vérifier l'absence de transformation en tumeur maligne (choriocarcinome)." },
        { order: 4, text: "Une patiente à 32 semaines d'aménorrhée se présente pour des saignements rouge vif, abondants et récidivants, sans aucune douleur abdominale. L'utérus est souple au palper. Quelle conduite la sage-femme doit-elle adopter ?", choiceA: "Réaliser immédiatement un toucher vaginal pour évaluer l'ouverture du col.", choiceB: "Suspecter un placenta praevia (placenta inséré trop bas) en priorité.", choiceC: "Réaliser une échographie obstétricale pour localiser précisément le placenta.", choiceD: "Déclencher l'accouchement.", choiceE: "Le toucher vaginal est formellement interdit car il peut déclencher une hémorragie massive.", correctAnswer: "B,C,E", explanation: "Devant des saignements indolores au troisième trimestre sur un utérus souple, le placenta praevia est le diagnostic principal. Le toucher vaginal est contre-indiqué tant que la position du placenta n'est pas connue." },
        { order: 5, text: "Une patiente à 35 semaines d'aménorrhée consulte pour une douleur abdominale brutale \"en coup de poignard\" avec un utérus dur et contracté en permanence. On note des saignements de faible abondance de sang noir. Quels sont les risques et caractéristiques ?", choiceA: "Il s'agit d'un hématome rétro-placentaire.", choiceB: "Le risque majeur pour la mère est un trouble grave de la coagulation.", choiceC: "La mort fœtale est une complication fréquente.", choiceD: "Le pronostic pour l'enfant est généralement excellent.", choiceE: "Une extraction de l'enfant en urgence par césarienne est souvent nécessaire.", correctAnswer: "A,B,C,E", explanation: "L'hématome rétro-placentaire est une urgence vitale. L'utérus 'ventre de bois' est le signe caractéristique. Il menace la vie de la mère (choc et hémorragie) et de l'enfant (arrêt des échanges d'oxygène)." },
        { order: 6, text: "Une sage-femme assiste à une rupture des membranes chez une patiente en travail. Immédiatement après, elle constate un saignement de sang rouge d'origine fœtale avec une chute brutale du rythme cardiaque de l'enfant. Quel diagnostic évoquer ?", choiceA: "Un placenta praevia.", choiceB: "Une hémorragie de Benckiser.", choiceC: "Une rupture utérine.", choiceD: "Cette pathologie survient spécifiquement lors de la rupture des membranes.", choiceE: "L'origine du sang est exclusivement maternelle.", correctAnswer: "B,D", explanation: "L'hémorragie de Benckiser correspond à la déchirure de vaisseaux fœtaux qui traversent les membranes. Le sang perdu est celui du fœtus, ce qui explique la gravité immédiate pour l'enfant." },
        { order: 7, text: "Concernant l'hémorragie de la délivrance, quels éléments sont exacts ?", choiceA: "Elle se définit par une perte de sang supérieure à 500 millilitres dans les 24 heures après l'accouchement.", choiceB: "Elle est considérée comme sévère si les pertes dépassent 1000 millilitres.", choiceC: "Elle concerne environ 50% des accouchements.", choiceD: "Elle est toujours évitable si l'on connaît les facteurs de risque de la patiente.", choiceE: "Dans la moitié des cas, il n'existe aucun facteur de risque identifié avant l'hémorragie.", correctAnswer: "A,B,E", explanation: "L'hémorragie de la délivrance est fréquente et souvent imprévisible. La surveillance de toutes les patientes pendant les deux heures suivant l'accouchement est donc capitale." },
        { order: 8, text: "Après l'expulsion complète du placenta et une vérification de l'utérus normale, une patiente continue de saigner abondamment. L'utérus reste mou. Quelles sont les causes possibles ?", choiceA: "Une atonie utérine (défaut de contraction du muscle utérin).", choiceB: "Une déchirure du col de l'utérus ou du vagin.", choiceC: "Des troubles de la coagulation sanguine.", choiceD: "Une infection urinaire foudroyante.", choiceE: "Une allergie au produit d'anesthésie.", correctAnswer: "A,B,C", explanation: "Si l'hémorragie persiste après la délivrance, la sage-femme doit suspecter en priorité l'atonie utérine, puis inspecter les parois vaginales et le col pour éliminer une plaie traumatique." },
        { order: 9, text: "Dans la prise en charge d'une hémorragie du post-partum qui persiste malgré les premiers soins, quels sont les traitements indiqués ?", choiceA: "Utilisation de l'ocytocine en perfusion continue.", choiceB: "Utilisation de la prostaglandine.", choiceC: "Administration d'antibiotiques par voie veineuse en cas de geste endo utérin.", choiceD: "Pose d'une sonde urinaire pour vider la vessie.", choiceE: "Prescription de médicaments pour arrêter la montée de lait.", correctAnswer: "A,B,C,D", explanation: "L'ocytocine est le traitement de première intention. En cas d'échec, la prostaglandine est introduite. La vidange vésicale et l'antibioprophylaxie sont des mesures associées systématiques." },
        { order: 10, text: "Une sage-femme réalise une \"délivrance dirigée\" pour prévenir l'hémorragie. Quelles sont les modalités correctes ?", choiceA: "Injecter 5 à 10 unités d'ocytocine au moment de la sortie de l'épaule de l'enfant.", choiceB: "Attendre l'expulsion totale du placenta pour injecter l'ocytocine.", choiceC: "Utiliser un sac de recueil gradué pour mesurer précisément les pertes de sang.", choiceD: "Surveiller la formation du globe utérin de sécurité pendant 2 heures.", choiceE: "Pratiquer un massage de l'utérus pour favoriser sa rétraction.", correctAnswer: "A,C,D,E", explanation: "L'injection précoce d'ocytocine réduit considérablement le risque d'atonie utérine et d'hémorragie grave." },
        { order: 11, text: "Une patiente à 32 semaines d'aménorrhée présente un placenta qui recouvre totalement le col. Elle a des saignements modérés et est de groupe sanguin O négatif. Quels éléments de prise en charge sont prévus ?", choiceA: "Repos strict au lit.", choiceB: "Administration de corticoïdes pour préparer les poumons de l'enfant.", choiceC: "Injection d'immunoglobulines anti-D.", choiceD: "Prévision d'une césarienne.", choiceE: "Vérification régulière de la dilatation par toucher vaginal.", correctAnswer: "A,B,C,D", explanation: "Le repos et la maturation pulmonaire sont essentiels avant 34 semaines. Le toucher vaginal est formellement contre-indiqué car il aggrave le saignement du placenta praevia." },
        { order: 12, text: "Une patiente présente un tableau d'hématome rétro-placentaire complet. Quels signes cliniques et biologiques la sage-femme observera-t-elle ?", choiceA: "Douleurs de l'utérus brutales, intenses et permanentes.", choiceB: "Utérus souple et relâché.", choiceC: "Sang noir, peu abondant et qui ne coagule pas.", choiceD: "Présence de protéines dans les urines à la bandelette urinaire en rapport avec l'étiologie.", choiceE: "Une patiente calme sans douleur avec des contractions espacées.", correctAnswer: "A,C,D", explanation: "L'hématome rétro-placentaire associe une douleur atroce, un utérus dur comme du bois et souvent des signes de prééclampsie (protéines dans les urines)." },
        { order: 13, text: "Lors de l'échographie d'une patiente suspecte de grossesse extra-utérine, quels signes sont en faveur du diagnostic ?", choiceA: "Un utérus vide alors que le test de grossesse est positif.", choiceB: "La présence d'une image avec une couronne blanche dans la trompe.", choiceC: "La présence de liquide dans le cul-de-sac de Douglas.", choiceD: "Un \"pseudo-sac\" (poche de liquide simple au centre de l'utérus).", choiceE: "Une image de masse hétérogène à côté de l'utérus.", correctAnswer: "A,B,C,D,E", explanation: "Tous ces signes, qu'ils soient directs (image dans la trompe) ou indirects (utérus vide, liquide dans le ventre), sont des signes en faveurs du diagnostic." },
        { order: 14, text: "Une patiente a été traitée pour une grossesse molaire il y a 2 mois. Ses taux d'hormone de grossesse stagnent depuis 3 semaines. Quelle complication doit être suspectée ?", choiceA: "Une nouvelle grossesse normale débutante.", choiceB: "Un choriocarcinome (évolution maligne).", choiceC: "Une môle hydatiforme.", choiceD: "Une simple fatigue passagère.", choiceE: "Une infection de la paroi utérine.", correctAnswer: "B", explanation: "La stagnation ou la remontée des taux d'hormone de grossesse après l'évacuation d'une môle indique que des cellules tumorales persistent ou se transforment en cancer." },
        { order: 15, text: "Une patiente de groupe sanguin B négatif fait une fausse couche spontanée à 9 semaines d'aménorrhée. Quelle est la conduite à tenir indispensable ?", choiceA: "Ne rien faire car il est trop tôt pour une immunisation.", choiceB: "Injecter des immunoglobulines anti-D dans un délai de 72 heures.", choiceC: "Vérifier que l'utérus est vide par une échographie.", choiceD: "Contrôler la baisse des hormones de grossesse.", choiceE: "Proposer une méthode de contraception dès que possible.", correctAnswer: "A,C,E", explanation: "Avant 12 SA, il n'est plus recommandé de donner un Anti-D car le risque d'alloimmunisation est quasi nul. On vérifie que l'utérus est vide et on discute d'une contraception." },
        { order: 16, text: "Suite à un choc hémorragique lors de son accouchement, une patiente présente une absence totale de montée laiteuse et une fatigue extrême. Quel diagnostic le document suggère-t-il ?", choiceA: "Une dépression du post-partum.", choiceB: "Un syndrome de Sheehan.", choiceC: "Une destruction de l'hypophyse par manque d'oxygène pendant le choc.", choiceD: "Une carence en fer sévère.", choiceE: "Une complication normale de l'hémorragie.", correctAnswer: "B,C", explanation: "Le syndrome de Sheehan est une nécrose de la glande hypophyse suite à une hémorragie massive. Il se manifeste par l'impossibilité d'allaiter et l'absence de retour des règles." },
        { order: 17, text: "Pour différencier un placenta praevia bas d'un hématome rétro-placentaire, quelles affirmations sont vraies ?", choiceA: "Le placenta praevia donne un utérus souple, l'hématome donne un utérus dur.", choiceB: "Le placenta praevia donne du sang rouge, l'hématome donne souvent du sang noir.", choiceC: "La souffrance de l'enfant est beaucoup plus fréquente et brutale en cas d'hématome.", choiceD: "Le placenta praevia est toujours très douloureux.", choiceE: "L'hématome est souvent lié à une hypertension artérielle.", correctAnswer: "A,B,C,E", explanation: "Le placenta praevia est classiquement indolore. L'hématome rétro-placentaire est une urgence douloureuse souvent associée à une maladie vasculaire de la mère." },
      ],
    },
  ],
};

async function replaceTheme(data: typeof GROSSESSE_DATA) {
  const existing = await prisma.theme.findFirst({
    where: { name: data.theme, language: 'FR', target: 'SAGE_FEMME' },
    include: { subThemes: true },
  });

  if (existing) {
    // Supprimer toutes les questions des sous-thèmes existants
    for (const st of existing.subThemes) {
      await prisma.question.deleteMany({ where: { subThemeId: st.id } });
    }
    // Supprimer les sous-thèmes
    await prisma.subTheme.deleteMany({ where: { themeId: existing.id } });
    console.log(`  ✓ Thème "${data.theme}" nettoyé`);
  } else {
    console.log(`  ! Thème "${data.theme}" non trouvé, création...`);
  }

  const themeId = existing?.id;

  for (const stData of data.subThemes) {
    let st = themeId ? await prisma.subTheme.findFirst({ where: { themeId, name: stData.name } }) : null;

    if (!st) {
      if (!themeId) {
        // Créer le thème si inexistant
        const newTheme = await prisma.theme.create({
          data: { name: data.theme, language: 'FR', target: 'SAGE_FEMME' },
        });
        st = await prisma.subTheme.create({ data: { name: stData.name, themeId: newTheme.id } });
      } else {
        st = await prisma.subTheme.create({ data: { name: stData.name, themeId } });
      }
    }

    await prisma.question.createMany({
      data: stData.questions.map(q => ({
        ...q,
        subThemeId: st!.id,
        isActive: true,
        choiceE: q.choiceE ?? '',
      })),
    });

    console.log(`    └─ ${stData.name} : ${stData.questions.length} questions importées`);
  }
}

async function main() {
  console.log('\n=== Correction thèmes GROSSESSE (SAGE_FEMME FR) ===\n');
  console.log('LA GROSSESSE NORMALE :');
  await replaceTheme(GROSSESSE_DATA);
  console.log('\nPrincipales complications de la grossesse :');
  await replaceTheme(COMPLICATIONS_DATA as any);
  console.log('\n✅ Import terminé');
}

main().catch(console.error).finally(() => prisma.$disconnect());
