const { PrismaClient } = require('@prisma/client');
const p = new PrismaClient();

const PATHO3 = 'cmqbmrvxq000yufl430smklkw';
const POSTPARTUM = 'cmqbmrw6a0012ufl4rbka3iwv';
const TRAVAIL = 'cmqbmrw240010ufl4d2nq4556';

const questions = [
  // ── Pathologies du troisième trimestre ──────────────────────────────────────
  {
    subThemeId: PATHO3,
    text: "Une patiente à 32 SA se présente pour des saignements de sang rouge vif, abondants et indolores. L'utérus est souple à la palpation et aucun signe de contraction n'est noté au monitoring.",
    choiceA: "Le diagnostic le plus probable est un placenta praevia.",
    choiceB: "Le toucher vaginal (TV) est formellement interdit avant d'avoir localisé le placenta.",
    choiceC: "L'échographie obstétricale permet de confirmer le type d'insertion",
    choiceD: "Une hospitalisation immédiate pour surveillance et repos est nécessaire.",
    choiceE: "On doit pratiquer une césarienne immédiate, quel que soit le volume de l'hémorragie.",
    correctAnswer: "A, B, C, D",
    explanation: "Le caractère indolore et le sang rouge sur utérus souple sont typiques du placenta praevia. Le TV est proscrit car il peut déclencher une hémorragie massive catastrophique en touchant les vaisseaux. L'extraction fœtale immédiate n'est indiquée qu'en cas d'hémorragie non contrôlée ou de souffrance fœtale.",
  },
  {
    subThemeId: PATHO3,
    text: "À 35 SA, une femme consulte pour une douleur abdominale brutale \"en coup de poignard\". L'utérus est dur, contracté en permanence (\"ventre de bois\") et vous notez un saignement de sang noir.",
    choiceA: "Il s'agit d'un hématome rétro-placentaire (HRP).",
    choiceB: "Le risque majeur pour la mère est un trouble grave de la coagulation (CIVD).",
    choiceC: "La mort fœtale in utero est une complication fréquente par arrêt des échanges gazeux.",
    choiceD: "Une césarienne en urgence absolue est généralement impérative.",
    choiceE: "C'est une pathologie qui survient préférentiellement en cas d'hypotension artérielle.",
    correctAnswer: "A, B, C, D",
    explanation: "L'HRP est une urgence vitale associant douleur atroce, contracture utérine permanente et sang noir. La spoliation de facteurs de coagulation mène à la coagulation intravasculaire disséminée (CIVD). L'hypertension artérielle (HTA) est le principal facteur favorisant, et non l'hypotension.",
  },
  {
    subThemeId: PATHO3,
    text: "Lors de la rupture artificielle des membranes en salle de naissance, vous observez un saignement rouge immédiat associé à une bradycardie fœtale brutale à 80 bpm. L'utérus est souple.",
    choiceA: "Il s'agit d'une hémorragie de Benckiser (rupture d'un vaisseau praevia).",
    choiceB: "Le sang perdu est d'origine exclusivement maternelle.",
    choiceC: "Cette pathologie est liée à une insertion vélamenteuse du cordon ombilical.",
    choiceD: "Une césarienne pour extraction immédiate est le seul recours pour la survie de l'enfant.",
    choiceE: "Le pronostic fœtal est généralement bon sous simple surveillance médicale.",
    correctAnswer: "A, C, D",
    explanation: "L'hémorragie de Benckiser survient lors de la déchirure de vaisseaux fœtaux qui traversent les membranes (insertion vélamenteuse). Le sang étant d'origine fœtale, l'enfant se vide de son sang en quelques minutes. L'extraction immédiate est impérative car le pronostic vital fœtal est engagé d'emblée.",
  },
  {
    subThemeId: PATHO3,
    text: "Vous examinez une patiente au repos lors de sa consultation du 9ème mois. Sa tension artérielle est mesurée à deux reprises à 145/95 mmHg. Elle ne signale aucune douleur.",
    choiceA: "Le diagnostic d'hypertension artérielle (HTA) gravidique est posé.",
    choiceB: "Le diagnostic nécessite impérativement une seule mesure supérieure à 140/90 mmHg.",
    choiceC: "L'HTA gravidique apparaît par définition après 20 SA.",
    choiceD: "On doit impérativement rechercher une protéinurie par bandelette urinaire.",
    choiceE: "L'alpha-méthyldopa (Aldomet) est un traitement antihypertenseur autorisé.",
    correctAnswer: "A, C, D, E",
    explanation: "L'HTA se définit par une tension >= 140/90 mmHg confirmée par deux mesures au repos. Elle est dite gravidique si elle apparaît après 20 SA et disparaît avant 6 semaines post-partum. La recherche de protéinurie est cruciale pour dépister le passage vers la pré-éclampsie. L'Aldomet est la molécule de référence pour son innocuité fœtale.",
  },
  {
    subThemeId: PATHO3,
    text: "Une patiente au 3ème trimestre présente une HTA à 150/95 mmHg associée à une protéinurie à la bandelette urinaire (notée 2+). Elle est primipare et son IMC est de 32.",
    choiceA: "Ce tableau clinique définit une pré-éclampsie.",
    choiceB: "La protéinurie est considérée comme pathologique si elle est >= 0,3 g/24h.",
    choiceC: "La nulliparité (primiparité) et l'obésité sont des facteurs de risque connus.",
    choiceD: "C'est une maladie de l'unité fœto-placentaire qui nécessite une surveillance fœtale.",
    choiceE: "Le traitement curatif définitif est la poursuite de la grossesse jusqu'au terme de 41 SA.",
    correctAnswer: "A, B, C, D",
    explanation: "L'association HTA et protéinurie signe la pré-éclampsie. Les facteurs de risque immunologiques (première grossesse) et métaboliques (obésité) majorent le risque. Le seul traitement curatif est l'évacuation de la grossesse (accouchement), car le placenta est à l'origine de la pathologie.",
  },
  {
    subThemeId: PATHO3,
    text: "Une patiente pré-éclamptique se plaint d'une douleur épigastrique intense en \"barre\", de céphalées et de phosphènes (mouches devant les yeux). Les réflexes ostéo-tendineux (ROT) sont vifs.",
    choiceA: "Ce sont des signes cliniques de pré-éclampsie sévère.",
    choiceB: "La douleur en barre traduit une souffrance hépatique (risque de HELLP ou hématome sous-capsulaire).",
    choiceC: "Il existe un risque imminent de crise d'éclampsie (convulsions).",
    choiceD: "L'extraction fœtale doit être envisagée rapidement pour sauvegarde maternelle.",
    choiceE: "On peut autoriser un retour à domicile sous simple surveillance par une sage-femme.",
    correctAnswer: "A, B, C, D",
    explanation: "La barre épigastrique et les signes neurologiques (céphalées, ROT vifs) marquent la sévérité et l'imminence de complications graves comme l'éclampsie. Une hospitalisation immédiate et une extraction fœtale rapide sont alors nécessaires pour sauver la mère.",
  },
  {
    subThemeId: PATHO3,
    text: "Le bilan biologique d'une patiente hypertensive montre une hémolyse (LDH élevés, schizocytes), des transaminases élevées (cytolyse) et des plaquettes à 85 000/mm³.",
    choiceA: "Elle présente un syndrome HELLP.",
    choiceB: "Le risque majeur pour la mère est la rupture du foie ou l'insuffisance rénale.",
    choiceC: "Il s'agit d'une variante grave de la pré-éclampsie sévère.",
    choiceD: "La présence de schizocytes confirme l'hémolyse mécanique.",
    choiceE: "Ce syndrome ne peut jamais survenir après l'accouchement.",
    correctAnswer: "A, B, C, D",
    explanation: "Le HELLP syndrome associe Hémolyse, cytolyse hépatique (Elevated Liver enzymes) et Thrombopénie (Low Platelets). C'est une forme de micro-angiopathie thrombotique grave. Contrairement aux idées reçues, environ 30 % des syndromes HELLP surviennent ou s'aggravent en post-partum.",
  },
  {
    subThemeId: PATHO3,
    text: "En salle de naissance, une patiente hypertendue présente brusquement des convulsions tonico-cloniques généralisées suivies d'une phase de coma.",
    choiceA: "Le diagnostic est une crise d'éclampsie.",
    choiceB: "Le sulfate de magnésium (MgSO4) est le traitement de référence pour stopper les crises.",
    choiceC: "On injecte un bolus de charge de 4g de MgSO4 en intraveineuse lente.",
    choiceD: "L'accouchement doit être réalisé impérativement par voie basse dans les 48 heures.",
    choiceE: "L'éclampsie est une urgence ultime pouvant entraîner le décès maternel.",
    correctAnswer: "A, B, C, E",
    explanation: "L'éclampsie est la complication convulsive de la pré-éclampsie. Le MgSO4 est supérieur aux benzodiazépines pour prévenir les récidives. L'accouchement est le seul traitement définitif et doit avoir lieu rapidement (dans les 12h) après stabilisation de la mère.",
  },
  {
    subThemeId: PATHO3,
    text: "Une patiente est sous traitement par sulfate de magnésium (MgSO4) pour une pré-éclampsie sévère. Quelles sont les modalités de surveillance et de sécurité ?",
    choiceA: "La disparition du réflexe rotulien est le premier signe de surdosage.",
    choiceB: "Une fréquence respiratoire inférieure à 12 (ou 16) cycles/min est un signe de gravité.",
    choiceC: "L'oligurie (< 30 mL/h) augmente le risque de toxicité car le magnésium est éliminé par les reins.",
    choiceD: "L'antidote à injecter en urgence est le gluconate de calcium (1g IV lente).",
    choiceE: "En cas de surdosage, il faut augmenter le débit de perfusion pour rincer le produit.",
    correctAnswer: "A, B, C, D",
    explanation: "La surveillance du sulfate de Magnésium est strictement clinique (ROT, FR, diurèse). En cas de signes de toxicité (bradypnée, abolition des ROT), il faut arrêter immédiatement le traitement et administrer l'antidote : le gluconate de calcium.",
  },
  {
    subThemeId: PATHO3,
    text: "Une patiente à 26 SA demande conseil pour une douleur dentaire. Vous lui rappelez les médicaments formellement contre-indiqués au 3ème trimestre.",
    choiceA: "Les Anti-Inflammatoires Non Stéroïdiens (AINS) sont proscrits après 24 SA.",
    choiceB: "Ils exposent au risque d'insuffisance rénale fœtale avec oligoamnios.",
    choiceC: "Ils peuvent provoquer une fermeture prématurée du canal artériel fœtal.",
    choiceD: "Une prise unique d'AINS après 24 SA peut être délétère pour le fœtus.",
    choiceE: "Le paracétamol est également formellement contre-indiqué après 24 SA.",
    correctAnswer: "A, B, C, D",
    explanation: "Les AINS sont fœtotoxiques (reins et cœur) de façon absolue dès le début du 6ème mois (24 SA) car ils inhibent la synthèse des prostaglandines vitales pour le fœtus. Le paracétamol reste l'antalgique de référence sans restriction pendant toute la grossesse.",
  },

  // ── Travail et Accouchement ──────────────────────────────────────────────────
  {
    subThemeId: TRAVAIL,
    text: "Une primipare de 24 ans, à 39 SA, est admise pour des contractions utérines douloureuses depuis 6 heures. À l'examen : col centré, souple, effacé à 80 %, ouvert à 4 cm. La présentation céphalique est fixée. Le rythme cardiaque fœtal (RCF) est normal.",
    choiceA: "La patiente est entrée en phase de latence du travail.",
    choiceB: "Elle est officiellement entrée en phase active du travail.",
    choiceC: "C'est le moment précis où l'on doit débuter le remplissage du partogramme.",
    choiceD: "Une surveillance de la dilatation doit être réalisée idéalement toutes les 2 à 4 heures.",
    choiceE: "La phase de latence peut physiologiquement durer jusqu'à 20 heures chez cette patiente.",
    correctAnswer: "B, C, D, E",
    explanation: "La phase active débute à une dilatation ≥ 4 cm. C'est à ce stade que le partogramme devient un outil de surveillance indispensable pour diagnostiquer précocement les dystocies. Chez une primipare, la phase de latence est considérée comme prolongée au-delà de 20 heures.",
  },
  {
    subThemeId: TRAVAIL,
    text: "Une multipare à 40 SA est en salle de naissance. À 10h, le col était à 5 cm. À 12h, l'examen montre une dilatation inchangée à 5 cm. La présentation est céphalique au détroit supérieur, mobile, et les membranes sont intactes (poche des eaux bombante).",
    choiceA: "On diagnostique une stagnation de la dilatation en phase active.",
    choiceB: "On doit réaliser une rupture artificielle des membranes (RAM) comme premier geste correcteur.",
    choiceC: "La RAM favorise l'appui de la présentation sur le col (réflexe de Ferguson).",
    choiceD: "On doit débuter immédiatement une perfusion d'ocytocine à forte dose.",
    choiceE: "La déambulation est recommandée pour optimiser la confrontation fœto-pelvienne.",
    correctAnswer: "A, B, C, E",
    explanation: "La stagnation est définie par l'absence de progression pendant 2 heures en phase active. La RAM est le geste de première ligne pour corriger cette dystocie à membranes intactes, stimulant la libération de prostaglandines endogènes. L'ocytocine ne doit être introduite qu'après rupture des membranes si l'hypocinésie persiste.",
  },
  {
    subThemeId: TRAVAIL,
    text: "Lors de l'expulsion chez une patiente diabétique, la tête fœtale se dégage mais semble s'écraser contre le périnée (signe de la tortue). Le menton reste bloqué et les épaules ne s'engagent pas malgré les efforts de poussée maternels.",
    choiceA: "Il s'agit d'une dystocie des épaules.",
    choiceB: "On doit pratiquer immédiatement une expression utérine (manœuvre de Kristeller).",
    choiceC: "La première mesure est la manœuvre de McRoberts (hyperflexion des cuisses).",
    choiceD: "On associe une pression sus-pubienne pour réduire le diamètre bi-acromial.",
    choiceE: "Il est impératif de tirer fortement sur la tête fœtale vers le bas.",
    correctAnswer: "A, C, D",
    explanation: "La manœuvre de McRoberts bascule le bassin et aplatit le promontoire sacré, facilitant l'engagement de l'épaule. L'expression utérine est formellement interdite car elle aggrave l'impaction des épaules contre la symphyse. Tirer sur la tête expose au risque de lésion du plexus brachial.",
  },
  {
    subThemeId: TRAVAIL,
    text: "Une parturiente de 32 ans rompt spontanément la poche des eaux. Immédiatement, le RCF chute brutalement à 70 bpm. Au toucher vaginal, vous percevez une boucle pulsatile en avant de la présentation céphalique encore haute.",
    choiceA: "Il s'agit d'une procidence du cordon.",
    choiceB: "On doit tenter de réinsérer le cordon à l'intérieur de l'utérus.",
    choiceC: "Il faut refouler manuellement la présentation fœtale jusqu'à l'extraction.",
    choiceD: "La patiente doit être installée en position genu-pectorale ou de Trendelenburg.",
    choiceE: "Une césarienne en urgence absolue est impérative si le fœtus est vivant.",
    correctAnswer: "A, C, D, E",
    explanation: "La procidence est une urgence extrême par anoxie circulatoire. Le refoulement de la tête lève la compression mécanique. La réinsertion du cordon est proscrite car elle provoque des spasmes artériels et aggrave l'hypoxie.",
  },
  {
    subThemeId: TRAVAIL,
    text: "Une patiente souhaite une épreuve utérine pour son deuxième enfant. Son premier est né par césarienne. Vous consultez le compte-rendu opératoire qui mentionne une \"hystérotomie corporéale verticale\" en raison d'une grande prématurité.",
    choiceA: "L'épreuve utérine (voie basse) est autorisée sous surveillance stricte.",
    choiceB: "La cicatrice corporéale est une contre-indication absolue à la voie basse.",
    choiceC: "Le risque de rupture utérine est particulièrement élevé sur ce type de cicatrice.",
    choiceD: "Une césarienne itérative programmée doit être organisée.",
    choiceE: "On peut utiliser l'ocytocine à forte dose pour accélérer le travail.",
    correctAnswer: "B, C, D",
    explanation: "La cicatrice corporéale (verticale) est trop fragile et impose une césarienne itérative systématique. L'épreuve utérine n'est envisageable que sur une cicatrice segmentaire transverse unique.",
  },
  {
    subThemeId: TRAVAIL,
    text: "En fin de travail chez une multipare, vous observez une ascension d'un anneau de rétraction sur l'utérus qui prend une forme de \"sablier\". La patiente est extrêmement agitée et se plaint d'une douleur vive sur sa cicatrice de césarienne antérieure.",
    choiceA: "Il s'agit de l'anneau de Bandl.",
    choiceB: "C'est un signe imminent de rupture utérine (syndrome de Bandl-Frommel).",
    choiceC: "On doit augmenter le débit d'ocytocine pour finir l'accouchement.",
    choiceD: "Une laparotomie en urgence est nécessaire.",
    choiceE: "On doit arrêter immédiatement toute perfusion d'ocytociques.",
    correctAnswer: "A, B, D, E",
    explanation: "Le syndrome de Bandl-Frommel est une urgence chirurgicale vitale précédant la rupture complète. L'arrêt des utérotoniques et la réanimation immédiate sont prioritaires.",
  },
  {
    subThemeId: TRAVAIL,
    text: "Au toucher vaginal chez une patiente à dilatation complète, vous identifiez nettement le menton, la bouche et la pyramide nasale. Le menton est orienté vers le sacrum de la mère.",
    choiceA: "Il s'agit d'une présentation de la face.",
    choiceB: "Le point de repère au toucher vaginal est le menton.",
    choiceC: "L'accouchement par voie basse est possible dans cette variété (mento-sacrée).",
    choiceD: "La variété mento-sacrée aboutit à un enclavement définitif du fœtus.",
    choiceE: "Une césarienne d'urgence doit être réalisée.",
    correctAnswer: "A, B, D, E",
    explanation: "La face n'est accouchable par voie basse que si le menton tourne vers l'avant (mento-pubien). En variété mento-sacrée, le cou est bloqué contre le sacrum, empêchant l'engagement.",
  },
  {
    subThemeId: TRAVAIL,
    text: "Lors de l'examen du col à 6 cm, vous percevez la grande fontanelle (bregma) au centre et la racine du nez. Vous ne sentez ni le menton, ni la petite fontanelle. Le diamètre d'engagement semble très large.",
    choiceA: "Il s'agit d'une présentation du front.",
    choiceB: "Le diamètre présenté est le sincipito-mentonnier (13,5 cm).",
    choiceC: "L'accouchement par voie basse est impossible car ce diamètre dépasse celui du bassin.",
    choiceD: "On peut attendre la rotation spontanée en sommet.",
    choiceE: "La césarienne est systématique dès que le diagnostic est confirmé.",
    correctAnswer: "A, B, C, E",
    explanation: "Le front (diamètre 13,5 cm) est une présentation \"non accouchable\" car il dépasse les dimensions du bassin maternel. Contrairement au bregma (12 cm), la voie basse est exclue.",
  },
  {
    subThemeId: TRAVAIL,
    text: "Le tracé du rythme cardiaque fœtal (RCF) montre des décélérations brusques en forme de \"V\", dont le début et la durée varient par rapport aux contractions. La variabilité reste normale entre les épisodes.",
    choiceA: "Ce sont des ralentissements variables.",
    choiceB: "Ils témoignent d'un incident funiculaire (compression du cordon).",
    choiceC: "Ils sont souvent associés à un oligoamnios (manque de liquide).",
    choiceD: "Le changement de position maternelle peut suffire à les corriger.",
    choiceE: "Ils sont pathognomoniques d'une hypoxie fœtale métabolique sévère.",
    correctAnswer: "A, B, C, D",
    explanation: "Les ralentissements variables signent la compression du cordon. Ils sont fréquents en cas d'oligoamnios par perte du \"coussin\" hydraulique. Le décubitus latéral peut lever la compression.",
  },
  {
    subThemeId: TRAVAIL,
    text: "Sur un monitoring, vous observez des ralentissements dont le point le plus bas (nadir) survient systématiquement 30 secondes après le sommet de la contraction, avec une remontée lente.",
    choiceA: "Ce sont des ralentissements tardifs (DIP 2).",
    choiceB: "Ils témoignent d'une hypoxie fœtale (insuffisance placentaire).",
    choiceC: "Ils imposent l'arrêt de l'ocytocine et la mise en décubitus latéral gauche.",
    choiceD: "Un pH au scalp peut être réalisé pour valider la tolérance.",
    choiceE: "Ils sont considérés comme normaux en fin de travail.",
    correctAnswer: "A, B, C, D",
    explanation: "Les DIP 2 sont pathologiques et signent un défaut d'oxygénation placentaire. Ils nécessitent des mesures correctrices immédiates et une évaluation du pH fœtal.",
  },

  // ── Post-partum et Délivrance ────────────────────────────────────────────────
  {
    subThemeId: POSTPARTUM,
    text: "Le bébé vient de naître, l'épaule antérieure est dégagée. Vous appliquez le protocole de GATPA (Gestion Active de la Troisième Phase de l'Accouchement).",
    choiceA: "On doit palper l'abdomen pour vérifier l'absence d'un second jumeau avant d'agir.",
    choiceB: "On injecte 10 UI d'ocytocine (Syntocinon) en IM immédiatement.",
    choiceC: "On réalise une traction contrôlée du cordon avec contre-traction utérine.",
    choiceD: "On attend 30 minutes avant de clamper le cordon.",
    choiceE: "Le massage utérin doit être répété toutes les 15 minutes pendant 2 heures.",
    correctAnswer: "A, B, C, E",
    explanation: "La GATPA réduit massivement le risque d'hémorragie. L'ocytocine prévient l'atonie et le massage favorise le globe de sécurité.",
  },
  {
    subThemeId: POSTPARTUM,
    text: "Le placenta n'est toujours pas expulsé 40 minutes après la naissance, malgré plusieurs tentatives de traction contrôlée pendant les contractions.",
    choiceA: "On diagnostique une rétention placentaire.",
    choiceB: "On doit réaliser une délivrance artificielle (DA) manuelle immédiatement.",
    choiceC: "Le geste doit être effectué dans des conditions d'asepsie rigoureuse.",
    choiceD: "Une antibioprophylaxie IV est recommandée (ex: Ampicilline + Métronidazole).",
    choiceE: "On peut attendre sans agir jusqu'à 2 heures si la patiente ne saigne pas.",
    correctAnswer: "A, B, C, D",
    explanation: "Au-delà de 30-40 min, l'extraction manuelle est requise pour prévenir l'hémorragie. L'antibiothérapie est systématique pour tout geste endo-utérin.",
  },
  {
    subThemeId: POSTPARTUM,
    text: "Une accouchée présente un saignement actif. Le sac de recueil gradué indique une perte de 650 mL dans les 24h post-partum. Elle commence à être pâle et tachycarde.",
    choiceA: "Il s'agit d'une hémorragie du post-partum (HPP).",
    choiceB: "Le seuil de définition de l'HPP est une perte de plus de 500 mL dans les 24h post-partum",
    choiceC: "L'HPP est dite sévère si les pertes dépassent 1000 mL dans les 24h post-partum",
    choiceD: "C'est une urgence vitale nécessitant une prise en charge multidisciplinaire.",
    choiceE: "On doit uniquement surveiller les constantes sans geste invasif.",
    correctAnswer: "A, B, C, D",
    explanation: "L'HPP est la première cause de mortalité maternelle. Toute perte > 500 mL dans les 24h post-partum impose l'activation immédiate du protocole d'urgence.",
  },
  {
    subThemeId: POSTPARTUM,
    text: "Après l'expulsion du placenta, l'utérus est perçu comme une masse molle (\"utérus de paille\") et le saignement persiste malgré le massage externe.",
    choiceA: "Le diagnostic est une atonie utérine.",
    choiceB: "On doit administrer des utérotoniques (ocytocine, sulprostone).",
    choiceC: "On doit réaliser une révision utérine (RU) manuelle pour vérifier la vacuité.",
    choiceD: "Une compression bimanuelle de l'utérus peut être salvatrice.",
    choiceE: "L'atonie est la cause la plus fréquente d'HPP (70% des cas).",
    correctAnswer: "A, B, C, D, E",
    explanation: "L'atonie est la cause majeure d'HPP. La RU élimine une rétention de débris et les utérotoniques visent à contracter le myomètre.",
  },
  {
    subThemeId: POSTPARTUM,
    text: "Lors de l'examen systématique du placenta, vous remarquez une zone de 3 cm de diamètre où les cotylédons semblent arrachés sur la face maternelle.",
    choiceA: "Il faut réaliser une révision utérine (RU) manuelle sans délai.",
    choiceB: "La rétention de débris placentaires expose au risque d'HPP et d'infection.",
    choiceC: "On doit prescrire une dose d'antibiotiques après la manœuvre.",
    choiceD: "On peut surveiller la patiente et attendre l'expulsion naturelle des débris.",
    choiceE: "L'administration d'utérotoniques complète utilement le geste.",
    correctAnswer: "A, B, C, E",
    explanation: "Un placenta incomplet impose une RU immédiate pour assurer l'hémostase et prévenir l'endométrite.",
  },
  {
    subThemeId: POSTPARTUM,
    text: "Face à une hémorragie massive foudroyante qui ne cède pas aux médicaments (ocytocine, sulprostone) en attendant le transfert au bloc.",
    choiceA: "On peut pratiquer une compression de l'aorte abdominale.",
    choiceB: "On appuie avec le poing fermé juste au-dessus et à gauche de l'ombilic.",
    choiceC: "L'efficacité est vérifiée par la disparition du pouls fémoral.",
    choiceD: "C'est une mesure de sauvetage temporaire.",
    choiceE: "On doit comprimer les deux artères radiales.",
    correctAnswer: "A, B, C, D",
    explanation: "La compression aortique permet de couper l'irrigation utérine en urgence extrême contre la colonne vertébrale.",
  },
  {
    subThemeId: POSTPARTUM,
    text: "Une masse rouge charnue apparaît brusquement à la vulve suite à une traction sur le cordon alors que le placenta n'est pas décollé. La patiente hurle de douleur et fait un malaise.",
    choiceA: "Il s'agit d'une inversion utérine aiguë.",
    choiceB: "On doit pratiquer une réduction manuelle immédiate (manœuvre de Johnson).",
    choiceC: "Il ne faut jamais administrer d'ocytocine AVANT la réduction de l'utérus.",
    choiceD: "Le choc neurogénique et hémorragique est une complication majeure.",
    choiceE: "On peut attendre tranquillement que l'anesthésiste arrive.",
    correctAnswer: "A, B, C, D",
    explanation: "L'inversion est une urgence vitale. L'ocytocine avant réduction bloquerait l'utérus en position inversée par rétraction du col.",
  },
  {
    subThemeId: POSTPARTUM,
    text: "Une accouchée ayant subi un choc hémorragique sévère (perte de 2 litres) se plaint à J3 d'une absence totale de montée laiteuse. Elle présente également une fatigue intense et une hypotension.",
    choiceA: "C'est le syndrome de Sheehan.",
    choiceB: "Il s'agit d'une nécrose ischémique de l'anté-hypophyse due au choc.",
    choiceC: "Cela peut se manifester par une aménorrhée définitive et une insuffisance surrénalienne.",
    choiceD: "C'est une complication très fréquente et sans gravité.",
    choiceE: "Une supplémentation hormonale substitutive sera nécessaire.",
    correctAnswer: "A, B, C, E",
    explanation: "Le syndrome de Sheehan est une séquelle grave de l'HPP massive par destruction de la glande hypophyse.",
  },
  {
    subThemeId: POSTPARTUM,
    text: "Au 4ème jour du post-partum, une patiente présente une fièvre à 39°C, un utérus mou et douloureux, et des lochies sales et fétides.",
    choiceA: "Le diagnostic le plus probable est une endométrite.",
    choiceB: "C'est une infection de la cavité utérine.",
    choiceC: "Une antibiothérapie par voie veineuse (ex: Augmentin) est nécessaire.",
    choiceD: "On doit réaliser un prélèvement vaginal et un ECBU.",
    choiceE: "Le traitement repose uniquement sur des douches vaginales.",
    correctAnswer: "A, B, C, D",
    explanation: "L'endométrite post-partum nécessite une prise en charge rapide pour éviter la septicémie. Elle est favorisée par les manœuvres endo-utérines.",
  },
  {
    subThemeId: POSTPARTUM,
    text: "Une patiente de 28 ans se plaint d'une douleur vive dans le mollet droit à J5 de son accouchement par césarienne. On note une fièvre modérée à 38°C et un mollet tendu.",
    choiceA: "On suspecte une thrombophlébite profonde.",
    choiceB: "Le risque majeur est l'embolie pulmonaire.",
    choiceC: "On doit réaliser un écho-Doppler veineux des membres inférieurs.",
    choiceD: "Un traitement anticoagulant (HBPM) est impératif si confirmée.",
    choiceE: "On doit encourager la patiente à faire du sport immédiatement.",
    correctAnswer: "A, B, C, D",
    explanation: "La douleur du mollet fébrile impose d'éliminer une phlébite. Le repos est préconisé avant l'anticoagulation pour éviter la migration du caillot.",
  },
];

async function run() {
  let inserted = 0, skipped = 0;
  for (const q of questions) {
    const exists = await p.question.findFirst({ where: { subThemeId: q.subThemeId, text: q.text } });
    if (exists) { skipped++; continue; }
    await p.question.create({ data: { ...q, isActive: true } });
    inserted++;
  }
  console.log(`✅ ${inserted} insérées, ${skipped} ignorées`);

  // Vérification finale
  const subs = await p.subTheme.findMany({
    where: { themeId: 'cmqbmrtmq0000ufl4mmnpc3eb' },
    include: { _count: { select: { questions: true } } }
  });
  subs.forEach(s => console.log(String(s._count.questions).padStart(4) + 'q - ' + s.name));

  await p.$disconnect();
}
run().catch(e => { console.error(e.message); p.$disconnect(); });
